67 add ground truth for cosmos region annotation tests
DARPA-ASKEM/knowledge-middleware pull request #115
Opened 2023-10-17 22:44 UTC by Sorrento110

# Description

* Added cosmos accuracy measures into the test pipeline. 

Resolves #67

2023-10-18 18:39 UTC, brandomr requested changes

2023-10-18 18:52 UTC, Sorrento110 commented on tests/scenarios/sidarthe/cosmos_ground_truth/stub.yaml
It was in the `reporting/scenarios/SIDARTHE` directory for the pipeline, I have moved it into both locations.

2023-10-24 13:23 UTC, brandomr reviewed
Looks good, just a couple comments

2023-10-24 13:23 UTC, brandomr commented on reporting/tests/report.py
> +                    result["accuracy"] = {"status_code": eval.status_code}
My worry is that the `status_code` might show up in the dashboard and cause some confusion. Or is it handled somewhere else? Maybe we should put `Failed` or something like that instead?

2023-10-24 13:23 UTC, brandomr commented on tests/test_e2e.py
> +    #         )
Can we just remove this block since it won't be used?

2023-10-24 19:27 UTC, brandomr approved these changes

2023-10-24 19:33 UTC, merged